### ISSUE TITLE
DEV: DX wishlist

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api-extra#21]
- [x] make a task which runs `pre-commit` without installing it (if requested?)
- [x] switch to `pixi run tests` (https://github.com/scientific-python/specs/pull/324)
- [x] Set up https://allcontributors.org
- [x] Set up codecov

**Comment by asmeurer** [comment]
I wasn't sure about these things (especially allcontributors) because it seemed to require access to the full data-apis organization, and I wasn't clear what that entailed. You should get feedback from @rgommers on this.

**Comment by lucascolley** [comment]
yeah, these are not high priority at all, I just thought it would be useful to keep track of them in an issue somewhere.

**Comment by rgommers** [comment]
I already enabled all-contributors when this repo was set up. Pixi sounds great, Codecov sounds fine too (as long as it's the config that doesn't comment but just adds the CI job entry with a link).

Pre-commit: sure, if you like it, go for it - you're doing most of the work here after all. As long as it's not mandatory and not hardcoded into the Pixi config preferably, because that will make it unusable for me. I'm happy for CI to fail and fix it up, or for pre-commit to add an extra auto-fix commit to my PR.

**Comment by lucascolley** [comment]
> Pre-commit: sure, if you like it, go for it - you're doing most of the work here after all. As long as it's not mandatory and not hardcoded into the Pixi config preferably, because that will make it unusable for me. 

Okay great, that's the request I was looking for. Currently, `pixi run lint` installs pre-commit locally, but I understand that that is too workflow-prescriptive (I just punted on fixing it until somebody asked).

**Comment by lucascolley** [comment]
> Codecov sounds fine too (as long as it's the config that doesn't comment but just adds the CI job entry with a link).

Sounds good - please could one of you go to https://app.codecov.io/gh/{your-username}/array-api-extra/new and add the `CODECOV_TOKEN` secret?

**Comment by rgommers** [comment]
Done:

![image](https://github.com/user-attachments/assets/3217617b-c500-4ac6-bfb8-bab3a9e0f478)
