### ISSUE TITLE
ENH: add `setdiff1d`

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api-extra#34]
These functions look like the most obvious candidates for this library from scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/439ea045ad44e6a09115dc23e9bf23db00ff41de/sklearn/utils/_array_api.py#L931-L982

cc @omarmanzoor @ogrisel @betatim

**Comment by lucascolley** [comment]
One problem is that these functions make use of `device` from array-api-compat. Either we need to restrict support in this library to array objects with the `device` attribute, or we vendor (copy) `device` and the functions it calls from array-api-compat.

**Comment by asmeurer** [comment]
I would propose `isin` for inclusion in the standard.

**Comment by lucascolley** [comment]
any thoughts on `setdiff1d` @asmeurer ?

**Comment by asmeurer** [comment]
I've never even heard of that function before. I guess if it has a lot of usage it could be proposed too, but otherwise I would assume it's a more niche function that would be appropriate. Also, isn't it straightforward to implement in terms of `isin` if that were added (though perhaps inefficiently)?

**Comment by lucascolley** [comment]
In scikit-learn they implement both in terms of `in1d`

**Comment by rgommers** [comment]
I'd also say that `setdiff1d` is too niche to consider for the standard. Adding it to `array-api-extra` seems like a better option.
